version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:6.0.6'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - 127.0.0.1:6379:6379
  mysql:
    image: 'bitnami/mysql:5.7.31'
    environment:
      - MYSQL_DATABASE=kids
      - MYSQL_ROOT_PASSWORD=gG693674yUqWzSAmNBLp67
    networks:
      - app-tier
    ports:
      - 3306:3306
    volumes:
      - ~/Desktop/Projects/kids-api/data/volumes/mysql:/bitnami/mysql/data
  app:
    image: 'pshaddel/node-white-label'
    environment:
      - DATABASE_URL=mysql://root:gG693674yUqWzSAmNBLp67@mysql:3306/content_white_label
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - 3000:3000
    networks:
      - app-tier
    depends_on:
      - mysql
      - redis